#include "inpdev_defs.autogen.h"



MOSS_ND char const* inpdev_btn_to_str( INPDEV_BTN inpdev_btn )
{
	// TODO: better?
	switch ( inpdev_btn )
	{
		case   0: return "Left Ctrl"     ;
		case   1: return "Function"      ;
		case   2: return "Left OS Key"   ;
		case   3: return "Left Alt"      ;
		case   4: return "Other4"        ;
		case   5: return "Spacebar"      ;
		case   6: return "Other6"        ;
		case   7: return "Other7"        ;
		case   8: return "Alt Gr"        ;
		case   9: return "Right OS Key"  ;
		case  10: return "Menu"          ;
		case  11: return "Right Ctrl"    ;
		case  12: return "Left Arrow"    ;
		case  13: return "Down Arrow"    ;
		case  14: return "Right Arrow"   ;
		case  15: return "Numpad 0"      ;
		case  16: return "Numpad ."      ;
		case  17: return "Numpad Enter"  ;
		case  32: return "Left Shift"    ;
		case  33: return "Other33"       ;
		case  34: return "z"             ;
		case  35: return "x"             ;
		case  36: return "c"             ;
		case  37: return "v"             ;
		case  38: return "b"             ;
		case  39: return "n"             ;
		case  40: return "m"             ;
		case  41: return ","             ;
		case  42: return "."             ;
		case  43: return "/"             ;
		case  44: return "Other44"       ;
		case  45: return "Right Shift"   ;
		case  46: return "Up Arrow"      ;
		case  47: return "Numpad 1"      ;
		case  48: return "Numpad 2"      ;
		case  49: return "Numpad 3"      ;
		case  64: return "Caps Lock"     ;
		case  65: return "a"             ;
		case  66: return "s"             ;
		case  67: return "d"             ;
		case  68: return "f"             ;
		case  69: return "g"             ;
		case  70: return "h"             ;
		case  71: return "j"             ;
		case  72: return "k"             ;
		case  73: return "l"             ;
		case  74: return ";"             ;
		case  75: return "'"             ;
		case  76: return "Other76"       ;
		case  77: return "Return"        ;
		case  78: return "Numpad 4"      ;
		case  79: return "Numpad 5"      ;
		case  80: return "Numpad 6"      ;
		case  81: return "Numpad +"      ;
		case  96: return "Tab"           ;
		case  97: return "q"             ;
		case  98: return "w"             ;
		case  99: return "e"             ;
		case 100: return "r"             ;
		case 101: return "t"             ;
		case 102: return "y"             ;
		case 103: return "u"             ;
		case 104: return "i"             ;
		case 105: return "o"             ;
		case 106: return "p"             ;
		case 107: return "["             ;
		case 108: return "]"             ;
		case 109: return "Other109"      ;
		case 110: return "\\"            ;
		case 111: return "Delete"        ;
		case 112: return "End"           ;
		case 113: return "Page Down"     ;
		case 114: return "Numpad 7"      ;
		case 115: return "Numpad 8"      ;
		case 116: return "Numpad 9"      ;
		case 128: return "`"             ;
		case 129: return "1"             ;
		case 130: return "2"             ;
		case 131: return "3"             ;
		case 132: return "4"             ;
		case 133: return "5"             ;
		case 134: return "6"             ;
		case 135: return "7"             ;
		case 136: return "8"             ;
		case 137: return "9"             ;
		case 138: return "0"             ;
		case 139: return "-"             ;
		case 140: return "="             ;
		case 141: return "Other141"      ;
		case 142: return "Backspace"     ;
		case 143: return "Insert"        ;
		case 144: return "Home"          ;
		case 145: return "Page Up"       ;
		case 146: return "Num Lock"      ;
		case 147: return "Numpad /"      ;
		case 148: return "Numpad *"      ;
		case 149: return "Numpad -"      ;
		case 160: return "Escape"        ;
		case 161: return "F1"            ;
		case 162: return "F2"            ;
		case 163: return "F3"            ;
		case 164: return "F4"            ;
		case 165: return "F5"            ;
		case 166: return "F6"            ;
		case 167: return "F7"            ;
		case 168: return "F8"            ;
		case 169: return "F9"            ;
		case 170: return "F10"           ;
		case 171: return "F11"           ;
		case 172: return "F12"           ;
		case 173: return "Print Screen"  ;
		case 174: return "Scroll Lock"   ;
		case 175: return "Pause / Break" ;
		case 192: return "Power"         ;
		case 193: return "Sleep"         ;
		case 194: return "Wake"          ;
		case 195: return "Stop"          ;
		case 196: return "Play / Pause"  ;
		case 197: return "Mute"          ;
		case 198: return "Volume Down"   ;
		case 199: return "Volume Up"     ;
		case 200: return "Media Select"  ;
		case 201: return "Previous Track";
		case 202: return "Next Track"    ;
		case 203: return "Calculator"    ;
		case 204: return "E-Mail"        ;
		case 205: return "My Computer"   ;
		case 206: return "www Back"      ;
		case 207: return "www Forward"   ;
		case 208: return "www Stop"      ;
		case 209: return "www Refresh"   ;
		case 210: return "www Home"      ;
		case 211: return "www Favorites" ;
		case 212: return "www Search"    ;
		case 224: return "Mouse Left"    ;
		case 225: return "Mouse Middle"  ;
		case 226: return "Mouse Right"   ;
		case 227: return "Mouse Button 4";
		case 228: return "Mouse Button 5";
		case 255: return "Invalid"       ;
		default:
		return "Invalid";
	}
}
